export const PLAN_LIST_REQUEST = 'PLAN_LIST_REQUEST'
export const PLAN_LIST_SUCCESS = 'PLAN_LIST_SUCCESS'
export const PLAN_LIST_FAIL = 'PLAN_LIST_FAIL'


export const PLAN_DETAILS_REQUEST = 'PLAN_DETAILS_REQUEST'
export const PLAN_DETAILS_SUCCESS = 'PLAN_DETAILS_SUCCESS'
export const PLAN_DETAILS_FAIL = 'PLAN_DETAILS_FAIL'


export const PLAN_DELETE_REQUEST = 'PLAN_DELETE_REQUEST'
export const PLAN_DELETE_SUCCESS = 'PLAN_DELETE_SUCCESS'
export const PLAN_DELETE_FAIL = 'PLAN_DELETE_FAIL'

export const PLAN_CREATE_REQUEST = 'PLAN_CREATE_REQUEST'
export const PLAN_CREATE_SUCCESS = 'PLAN_CREATE_SUCCESS'
export const PLAN_CREATE_FAIL = 'PLAN_CREATE_FAIL'
export const PLAN_CREATE_RESET = 'PLAN_CREATE_RESET'


export const PLAN_UPDATE_REQUEST = 'PLAN_UPDATE_REQUEST'
export const PLAN_UPDATE_SUCCESS = 'PLAN_UPDATE_SUCCESS'
export const PLAN_UPDATE_FAIL = 'PLAN_UPDATE_FAIL'
export const PLAN_UPDATE_RESET = 'PLAN_UPDATE_RESET'


export const PLAN_CREATE_REVIEW_REQUEST = 'PLAN_CREATE_REVIEW_REQUEST'
export const PLAN_CREATE_REVIEW_SUCCESS = 'PLAN_CREATE_REVIEW_SUCCESS'
export const PLAN_CREATE_REVIEW_FAIL = 'PLAN_CREATE_REVIEW_FAIL'
export const PLAN_CREATE_REVIEW_RESET = 'PLAN_CREATE_REVIEW_RESET'

export const PLAN_TOP_REQUEST = 'PLAN_TOP_REQUEST'
export const PLAN_TOP_SUCCESS = 'PLAN_TOP_SUCCESS'
export const PLAN_TOP_FAIL = 'PLAN_TOP_FAIL'


