export const PROFILE_LIST_REQUEST = 'PROFILE_LIST_REQUEST';
export const PROFILE_LIST_SUCCESS = 'PROFILE_LIST_SUCCESS';
export const PROFILE_LIST_FAIL = 'PROFILE_LIST_FAIL';

export const PROFILE_DETAILS_REQUEST = 'PROFILE_DETAILS_REQUEST';
export const PROFILE_DETAILS_SUCCESS = 'PROFILE_DETAILS_SUCCESS';
export const PROFILE_DETAILS_FAIL = 'PROFILE_DETAILS_FAIL';

export const PROFILE_DELETE_REQUEST = 'PROFILE_DELETE_REQUEST';
export const PROFILE_DELETE_SUCCESS = 'PROFILE_DELETE_SUCCESS';
export const PROFILE_DELETE_FAIL = 'PROFILE_DELETE_FAIL';

export const PROFILE_CREATE_REQUEST = 'PROFILE_CREATE_REQUEST';
export const PROFILE_CREATE_SUCCESS = 'PROFILE_CREATE_SUCCESS';
export const PROFILE_CREATE_FAIL = 'PROFILE_CREATE_FAIL';
export const PROFILE_CREATE_RESET = 'PROFILE_CREATE_RESET';

export const PROFILE_UPDATE_REQUEST = 'PROFILE_UPDATE_REQUEST';
export const PROFILE_UPDATE_SUCCESS = 'PROFILE_UPDATE_SUCCESS';
export const PROFILE_UPDATE_FAIL = 'PROFILE_UPDATE_FAIL';
export const PROFILE_UPDATE_RESET = 'PROFILE_UPDATE_RESET';

export const PROFILE_CREATE_REVIEW_REQUEST = 'PROFILE_CREATE_REVIEW_REQUEST';
export const PROFILE_CREATE_REVIEW_SUCCESS = 'PROFILE_CREATE_REVIEW_SUCCESS';
export const PROFILE_CREATE_REVIEW_FAIL = 'PROFILE_CREATE_REVIEW_FAIL';
export const PROFILE_CREATE_REVIEW_RESET = 'PROFILE_CREATE_REVIEW_RESET';

export const PROFILE_TOP_REQUEST = 'PROFILE_TOP_REQUEST';
export const PROFILE_TOP_SUCCESS = 'PROFILE_TOP_SUCCESS';
export const PROFILE_TOP_FAIL = 'PROFILE_TOP_FAIL';


export const PROFILE_HEART_REQUEST = 'PROFILE_HEART_REQUEST';
export const PROFILE_HEART_SUCCESS = 'PROFILE_HEART_SUCCESS';
export const PROFILE_HEART_FAIL = 'PROFILE_HEART_FAIL';

export const PROFILE_HEART_LIST_REQUEST = 'PROFILE_HEART_LIST_REQUEST';
export const PROFILE_HEART_LIST_SUCCESS = 'PROFILE_HEART_LIST_SUCCESS';
export const PROFILE_HEART_LIST_FAIL = 'PROFILE_HEART_LIST_FAIL';

export const HEART_UPDATE_REQUEST = 'HEART_UPDATE_REQUEST';
export const HEART_UPDATE_SUCCESS = 'HEART_UPDATE_SUCCESS';
export const HEART_UPDATE_FAIL = 'HEART_UPDATE_FAIL';
export const HEART_UPDATE_RESET = 'HEART_UPDATE_RESET';

export const HEART_DELETE_REQUEST = 'HEART_DELETE_REQUEST';
export const HEART_DELETE_SUCCESS = 'HEART_DELETE_SUCCESS';
export const HEART_DELETE_FAIL = 'HEART_DELETE_FAIL';
